<?php

return [
    'keywords' => [
        'bricolage', 'outil', 'vis', 'perceuse', 'tournevis', 'bois',
        'clou', 'marteau', 'poncer', 'peindre', 'visser', 'couper', 'scie',
        'mètre', 'niveau', 'meuble', 'étagère', 'mur', 'plafond', 'sol',
        'carrelage', 'peinture', 'enduit', 'joint', 'colle', 'pinceau',
        'rouleau', 'ponceuse', 'visseuse', 'perforateur', 'cloueur', 'meuleuse',
        'scie-sauteuse', 'scie-circulaire', 'rabot', 'lime', 'papier-verre',
        'marquage', 'gabarit', 'plan', 'planche', 'établi', 'étau', 'boulon',
        'écrou', 'cheville', 'clé', 'clé-plate', 'clé-à-molette', 'douille',
        'serre-joint', 'cutter', 'colle-bois', 'silicone', 'jointure', 'plâtre',
        'maçonnerie', 'menuiserie', 'électricité', 'plomberie', 'chauffage',
        'isolation', 'toiture', 'gouttière', 'mur-placo', 'placo', 'cloison',
        'lambris', 'parquet', 'stratifié', 'carrelette', 'découpe', 'rainure',
        'tenon', 'mortaise', 'assemblage', 'charnière', 'poignée', 'porte',
        'fenêtre', 'verre', 'joint-silicone', 'réparation', 'rénovation',
        'aménagement', 'atelier', 'garage', 'jardin', 'terrasse', 'pergola',
        'abri', 'palette', 'recyclage', 'customisation', 'peinture-bois',
        'vernis', 'lasure', 'teinte', 'protection-bois', 'entretien',
        'outillage', 'coffret-outils', 'mesure', 'traçage', 'décoration',
        'amélioration', 'installation', 'montage', 'démontage', 'perçage',
        'fixation', 'collage', 'scellement', 'mastic', 'pistolet-colle',
        'pistolet-peinture', 'bande-masquage', 'aspirateur-chantier',
        'étanchéité', 'niveau-laser', 'laser', 'bulle', 'tuto-bricolage',
        'guide-bricolage', 'astuce-bricolage', 'truc-maison', 'réparation-maison',
        'déco-maison', 'meuble-diy', 'meuble-sur-mesure', 'plan-de-travail',
        'sciage', 'forage', 'ponçage', 'vernissage', 'assemblage-bois',
        'tablette-murale', 'étagère-flottante', 'cadre-bois', 'lampe-diy',
        'récupération', 'outil-multi', 'outil-electroportatif', 'batterie',
        'chargeur-outil', 'outil-manu', 'boîte-à-outils', 'sac-à-outils',
        'marteau-piqueur', 'burin', 'ciseau-bois', 'scie-japonaise',
        'rabot-electrique', 'presse', 'agrafeuse', 'cloueur-electrique',
        'ponceuse-orbitale', 'ponceuse-bande', 'meule', 'disqueuse',
        'aspirateur-eau-poussière', 'masque-protection', 'gants-travail',
        'lunettes-protection', 'chaussures-securité', 'tablier-bricolage',
        'tapis-atelier', 'établi-pliable', 'rangement-outils', 'boîte-rangement',
        'trousse-outils', 'projecteur-led', 'rallonge-electrique',
        'enrouleur', 'prise', 'interrupteur', 'câble', 'fil-electrique',
        'domotique', 'smart-home', 'capteur', 'réseau-maison', 'petit-travaux',
        'grands-travaux', 'chantier', 'devis-bricolage', 'tutoriel-video',
        'projet-diy', 'idée-bricolage', 'création-maison', 'réutilisation'
    ],

    'stop_words' => [
        'le', 'la', 'les', 'un', 'une', 'des', 'du', 'de', 'd',
        'je', 'tu', 'il', 'elle', 'on', 'nous', 'vous', 'ils', 'elles',
        'me', 'te', 'se', 'nous', 'vous', 'y', 'en',
        'ce', 'cet', 'cette', 'ces',
        'mon', 'ton', 'son', 'ma', 'ta', 'sa', 'mes', 'tes', 'ses',
        'notre', 'votre', 'leur', 'nos', 'vos', 'leurs',
        'à', 'au', 'aux', 'avec', 'sans', 'sous', 'sur', 'dans', 'en',
        'par', 'pour', 'vers', 'chez', 'depuis', 'pendant',
        'et', 'ou', 'mais', 'donc', 'or', 'ni', 'car', 'que', 'qu',
        'comme', 'lorsque', 'puisque', 'quoique',
        'ne', 'pas', 'plus', 'très', 'trop', 'moins', 'bien', 'mal',
        'vraiment', 'assez', 'beaucoup', 'toujours', 'souvent',
        'jamais', 'parfois', 'aussitôt', 'avant', 'après', 'maintenant',
        'alors', 'ainsi', 'donc', 'pourtant', 'cependant',
        'est', 'sont', 'était', 'étaient', 'sera', 'seront', 'a', 'as',
        'avait', 'ont', 'aura', 'auront', 'fait', 'font', 'ferait',
        'peut', 'doit', 'veut', 'dit', 'dis', 'dirait', 'voit', 'vois',
        'pense', 'crois', 'sait', 'connaît',
        'bonjour', 'salut', 'coucou', 'hello', 'merci', 'ok', 'daccord',
        'voilà', 'voici', 'alors', 'donc', 'ensuite', 'puis', 'finalement',
        'bref', 'enfin', 'quoi', 'qui', 'où', 'quand', 'comment',
        'pourquoi', 'combien', 'quel', 'quelle', 'quels', 'quelles',
        'cest', 'cétait', 'ceci', 'cela', 'ça', 'certains', 'plusieurs',
        'chaque', 'tout', 'tous', 'toute', 'toutes', 'rien', 'personne',
        'quelque', 'quelques', 'même', 'autres', 'autre', 'chaque',
        'aucun', 'aucune', 'plusieurs', 'quelques', 'certain',
        'premièrement', 'deuxièmement', 'troisièmement', 'ensuite',
        'par ailleurs', 'de plus', 'en outre', 'par contre',
        'en revanche', 'néanmoins', 'toutefois', 'dune part',
        'dautre part', 'en conclusion', 'pour conclure', 'finalement',
        'aujourdhui', 'hier', 'demain', 'maintenant', 'tout à lheure',
        'bientôt', 'tôt', 'tard', 'longtemps', 'brièvement',
        'bienvenue', 'sommes', 'ici', 'voir' , 'va', 'vidéo', 'mettre', 'éventuellement',
        'pouvoir', 'si', 'plaisir', 'youtube', 'pouce', 'bleu', 'vérifiez', 'celle', 'passer', 'c', 'l', 's', 'j', 'n',
        'là', 'ci', 'ce', 'sûr', 'abonner', ''
    ]
];
