<?php

return [
    'keywords' => [
        'bricolage', 'outil', 'vis', 'perceuse', 'tournevis', 'bois',
        'clou', 'marteau', 'poncer', 'peindre', 'visser', 'couper', 'scie',
        'mètre', 'niveau', 'meuble', 'étagère', 'mur', 'plafond', 'sol',
        'carrelage', 'peinture', 'enduit', 'joint', 'colle', 'pinceau',
        'rouleau', 'ponceuse', 'visseuse', 'perforateur', 'cloueur', 'meuleuse',
        'scie-sauteuse', 'scie-circulaire', 'rabot', 'lime', 'papier-verre',
        'marquage', 'gabarit', 'plan', 'planche', 'établi', 'étau', 'boulon',
        'écrou', 'cheville', 'clé', 'clé-plate', 'clé-à-molette', 'douille',
        'serre-joint', 'cutter', 'colle-bois', 'silicone', 'jointure', 'plâtre',
        'maçonnerie', 'menuiserie', 'électricité', 'plomberie', 'chauffage',
        'isolation', 'toiture', 'gouttière', 'mur-placo', 'placo', 'cloison',
        'lambris', 'parquet', 'stratifié', 'carrelette', 'découpe', 'rainure',
        'tenon', 'mortaise', 'assemblage', 'charnière', 'poignée', 'porte',
        'fenêtre', 'verre', 'joint-silicone', 'réparation', 'rénovation',
        'aménagement', 'atelier', 'garage', 'jardin', 'terrasse', 'pergola',
        'abri', 'palette', 'recyclage', 'customisation', 'peinture-bois',
        'vernis', 'lasure', 'teinte', 'protection-bois', 'entretien',
        'outillage', 'coffret-outils', 'mesure', 'traçage', 'décoration',
        'amélioration', 'installation', 'montage', 'démontage', 'perçage',
        'fixation', 'collage', 'scellement', 'mastic', 'pistolet-colle',
        'pistolet-peinture', 'bande-masquage', 'aspirateur-chantier',
        'étanchéité', 'niveau-laser', 'laser', 'bulle', 'tuto-bricolage',
        'guide-bricolage', 'astuce-bricolage', 'truc-maison', 'réparation-maison',
        'déco-maison', 'meuble-diy', 'meuble-sur-mesure', 'plan-de-travail',
        'sciage', 'forage', 'ponçage', 'vernissage', 'assemblage-bois',
        'tablette-murale', 'étagère-flottante', 'cadre-bois', 'lampe-diy',
        'récupération', 'outil-multi', 'outil-electroportatif', 'batterie',
        'chargeur-outil', 'outil-manu', 'boîte-à-outils', 'sac-à-outils',
        'marteau-piqueur', 'burin', 'ciseau-bois', 'scie-japonaise',
        'rabot-electrique', 'presse', 'agrafeuse', 'cloueur-electrique',
        'ponceuse-orbitale', 'ponceuse-bande', 'meule', 'disqueuse',
        'aspirateur-eau-poussière', 'masque-protection', 'gants-travail',
        'lunettes-protection', 'chaussures-securité', 'tablier-bricolage',
        'tapis-atelier', 'établi-pliable', 'rangement-outils', 'boîte-rangement',
        'trousse-outils', 'projecteur-led', 'rallonge-electrique',
        'enrouleur', 'prise', 'interrupteur', 'câble', 'fil-electrique',
        'domotique', 'smart-home', 'capteur', 'réseau-maison', 'petit-travaux',
        'grands-travaux', 'chantier', 'devis-bricolage', 'tutoriel-video',
        'projet-diy', 'idée-bricolage', 'création-maison', 'réutilisation'
    ]
];
